package io.github.achirdlabs.rift.dsl;

import io.github.achirdlabs.rift.model.Response;
import io.github.achirdlabs.rift.model.RiftResponseExtension;

import java.util.Optional;

/**
 * A response entirely generated by a {@code _rift} script, with no {@code is} block — produced by
 * {@link RiftDsl#script(Script)}: a terminal {@link ResponseSpec} variant with no chain methods.
 */
public final class ScriptSpec implements ResponseSpec {

    private final Script script;

    private ScriptSpec(Script script) {
        this.script = script;
    }

    static ScriptSpec of(Script script) {
        return new ScriptSpec(script);
    }

    @Override
    public Response build() {
        RiftResponseExtension extension = new RiftResponseExtension(Optional.empty(), Optional.of(script.toConfig()), false);
        return new Response.RiftScript(extension);
    }
}
