package io.github.etacassiopeia.rift.model;

import io.github.etacassiopeia.rift.json.JsonObject;
import io.github.etacassiopeia.rift.json.JsonString;
import io.github.etacassiopeia.rift.json.JsonValue;

import java.util.Optional;

/**
 * A stub response. Exactly one of {@code is}/{@code proxy}/{@code inject}/{@code fault} is
 * present, or the response is generated entirely by a {@code _rift} script (no {@code is} block).
 * Priority when more than one is present, matching the engine: {@code is} &gt; {@code proxy} &gt;
 * {@code inject} &gt; {@code fault} &gt; script-only. A response object with none of these present
 * defaults to an empty 200 {@code is} response.
 */
public sealed interface Response {

    record Is(IsResponse is, Behaviors behaviors, Optional<RiftResponseExtension> rift) implements Response {
        public Is {
            java.util.Objects.requireNonNull(is, "is");
            java.util.Objects.requireNonNull(behaviors, "behaviors");
            java.util.Objects.requireNonNull(rift, "rift");
        }
    }

    record Proxy(ProxyResponse proxy) implements Response {}

    record Inject(String script) implements Response {}

    record Fault(String fault) implements Response {}

    /** Rift script-only response: no {@code is} block, the response is generated by the script. */
    record RiftScript(RiftResponseExtension rift) implements Response {}

    static Response read(JsonObject obj) {
        if (obj.get("is") != null) {
            return new Is(
                    IsResponse.read(JsonSupport.requireObject(obj.get("is"), "is")),
                    readBehaviors(obj),
                    readRift(obj));
        }
        if (obj.get("proxy") != null) {
            return new Proxy(ProxyResponse.read(JsonSupport.requireObject(obj.get("proxy"), "proxy")));
        }
        if (obj.get("inject") != null) {
            return new Inject(JsonSupport.requireString(obj, "inject"));
        }
        if (obj.get("fault") != null) {
            return new Fault(JsonSupport.requireString(obj, "fault"));
        }
        if (obj.get("_rift") != null) {
            return new RiftScript(RiftResponseExtension.read(JsonSupport.requireObject(obj.get("_rift"), "_rift")));
        }
        return new Is(new IsResponse(IsResponse.DEFAULT_STATUS_CODE), Behaviors.EMPTY, Optional.empty());
    }

    /**
     * Reads behaviors from either shape: the {@code _behaviors} object every fixture uses, or the
     * {@code behaviors} array-of-single-key-objects the engine itself emits in {@code GET /imposters}
     * output. Accepting the array form keeps consuming engine output from silently dropping them.
     */
    private static Behaviors readBehaviors(JsonObject obj) {
        JsonValue underscore = obj.get("_behaviors");
        if (underscore != null) {
            return Behaviors.read(JsonSupport.requireObject(underscore, "_behaviors"));
        }
        JsonValue array = obj.get("behaviors");
        if (array != null) {
            return Behaviors.readArray(JsonSupport.requireArray(array, "behaviors"));
        }
        return Behaviors.EMPTY;
    }

    private static Optional<RiftResponseExtension> readRift(JsonObject obj) {
        JsonValue rift = obj.get("_rift");
        return Optional.ofNullable(rift).map(v -> RiftResponseExtension.read(JsonSupport.requireObject(v, "_rift")));
    }

    /**
     * Writes this response. Uses an {@code instanceof} chain rather than a pattern-matching
     * {@code switch}: the latter is still a preview feature at the Java 17 release level this
     * module compiles against (finalized only in Java 21).
     */
    default JsonObject toJsonValue() {
        JsonObject.Builder builder = JsonObject.builder();
        if (this instanceof Is is) {
            builder.put("is", is.is().toJsonValue());
            if (!is.behaviors().isEmpty()) {
                builder.put("_behaviors", is.behaviors().toJsonValue());
            }
            is.rift().ifPresent(v -> builder.put("_rift", v.toJsonValue()));
        } else if (this instanceof Proxy proxy) {
            builder.put("proxy", proxy.proxy().toJsonValue());
        } else if (this instanceof Inject inject) {
            builder.put("inject", new JsonString(inject.script()));
        } else if (this instanceof Fault fault) {
            builder.put("fault", new JsonString(fault.fault()));
        } else if (this instanceof RiftScript riftScript) {
            builder.put("_rift", riftScript.rift().toJsonValue());
        } else {
            throw new IllegalStateException("unreachable: " + this);
        }
        return builder.build();
    }
}
